import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { PdfBooks } from 'src/Entities/pdf_books.entity';
import { ImagesService } from 'src/images/images.service';
import { PdfBooksModel } from 'src/Models/pdf_books.model';
import { Repository } from 'typeorm';

@Injectable()
export class PdfBooksService {
    constructor(
        @InjectRepository(PdfBooks)
        private readonly pdfBooksRepository: Repository<PdfBooks>,
        private readonly imagesService: ImagesService
    ) {}

    async find() {
        try {
            await this.ensurePdfBooksSchema();
            return { success: true, datas: await this.pdfBooksRepository.find({ relations: ['books'] }) };
        } catch {
            throw new HttpException(`Cannot GET /pdf_books`, HttpStatus.NOT_FOUND);
        }
    }

    async findOne(id: number) {
        try {
            await this.ensurePdfBooksSchema();
            return {
                success: true,
                datas: await this.pdfBooksRepository.findOne({ where: { id: id }, relations: ['books'] }),
            };
        } catch {
            throw new HttpException(`Cannot GET /pdf_books/${id}`, HttpStatus.NOT_FOUND);
        }
    }

    async create(pdfBooks: PdfBooksModel, files) {
        try {
            await this.ensurePdfBooksSchema();
            const oldPdfBook = await this.pdfBooksRepository.findOne({
                where: { booksId: pdfBooks.booksId },
            });
            if (!oldPdfBook) {
                if (files && files.file && files.file.length) {
                    pdfBooks.file = this.imagesService.savePdf(files.file[0]);
                }
                return { success: true, datas: await this.pdfBooksRepository.save(pdfBooks) };
            }
            return { success: false };
        } catch {
            throw new HttpException(`Cannot POST /pdf_books`, HttpStatus.NOT_FOUND);
        }
    }

    async update(pdfBooks: PdfBooksModel, files) {
        try {
            await this.ensurePdfBooksSchema();
            const oldPdfBook = await this.pdfBooksRepository.findOne({
                where: { booksId: pdfBooks.booksId },
            });
            if (!oldPdfBook || Number(oldPdfBook.id) === Number(pdfBooks.id)) {
                if (files && files.file && files.file.length) {
                    pdfBooks.file = this.imagesService.savePdf(files.file[0]);
                }
                return { success: true, datas: await this.pdfBooksRepository.update(pdfBooks.id, pdfBooks) };
            }
            return { success: false };
        } catch {
            throw new HttpException(`Cannot PUT /pdf_books`, HttpStatus.NOT_FOUND);
        }
    }

    async delete(id: number) {
        try {
            await this.ensurePdfBooksSchema();
            const pdfBooks = await this.pdfBooksRepository.findOne({ where: { id: id } });
            if (pdfBooks) {
                return { success: true, datas: await this.pdfBooksRepository.delete(id) };
            }
            return { success: false };
        } catch {
            throw new HttpException(`Cannot DELETE /pdf_books/${id}`, HttpStatus.NOT_FOUND);
        }
    }

    private async ensurePdfBooksSchema() {
        await this.pdfBooksRepository.query(`
            CREATE TABLE IF NOT EXISTS public.pdf_books
            (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "booksId" integer,
                file text,
                CONSTRAINT pdf_books_pkey PRIMARY KEY (id),
                CONSTRAINT pdf_books_books_key FOREIGN KEY ("booksId")
                    REFERENCES public.books (id) MATCH SIMPLE
                    ON UPDATE CASCADE
                    ON DELETE CASCADE
                    NOT VALID
            )
        `);
    }
}
