import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Books } from 'src/Entities/books.entity';
import { ImagesService } from 'src/images/images.service';
import { BooksModel } from 'src/Models/books.model';
import { Repository } from 'typeorm';

@Injectable()
export class BooksService {
    private booksSchemaReady = false;

    constructor(
        @InjectRepository(Books)
        private readonly booksRepository: Repository<Books>,
        private readonly imagesService: ImagesService
    ) {}

    private async ensureBooksSchema() {
        if (this.booksSchemaReady) {
            return;
        }

        await this.booksRepository.query(`
            ALTER TABLE public.books
            ADD COLUMN IF NOT EXISTS show_in_app boolean NOT NULL DEFAULT true
        `);
        await this.booksRepository.query(`
            ALTER TABLE public.books
            ADD COLUMN IF NOT EXISTS language text DEFAULT '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'
        `);
        await this.booksRepository.query(`
            UPDATE public.books
            SET language = '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'
            WHERE language IS NULL OR btrim(language) = '' OR language = '???????'
        `);
        await this.booksRepository.query(`
            CREATE TABLE IF NOT EXISTS public.pdf_books
            (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "booksId" integer,
                file text,
                CONSTRAINT pdf_books_pkey PRIMARY KEY (id),
                CONSTRAINT pdf_books_books_key FOREIGN KEY ("booksId")
                    REFERENCES public.books (id) MATCH SIMPLE
                    ON UPDATE CASCADE
                    ON DELETE CASCADE
                    NOT VALID
            )
        `);
        this.booksSchemaReady = true;
    }

    private normalizeShowInApp(books: BooksModel, defaultValue?: boolean) {
        const value = books.show_in_app as unknown;
        if (value === undefined || value === null || value === '') {
            if (defaultValue !== undefined) {
                books.show_in_app = defaultValue;
            }
            return;
        }

        if (typeof value === 'boolean') {
            return;
        }

        const normalized = String(value).trim().toLowerCase();
        books.show_in_app = !['false', '0', 'off', 'no'].includes(normalized);
    }

    private normalizeLanguage(books: BooksModel) {
        const value = String(books.language ?? '').trim();
        books.language = value || '\u0420\u0443\u0441\u0441\u043a\u0438\u0439';
    }

    private booleanFromValue(value: unknown, defaultValue = true) {
        if (value === undefined || value === null || value === '') {
            return defaultValue;
        }

        if (typeof value === 'boolean') {
            return value;
        }

        const normalized = String(value).trim().toLowerCase();
        return !['false', '0', 'off', 'no'].includes(normalized);
    }

    async find() {
        try {
            await this.ensureBooksSchema();
            return { success: true, datas: await this.booksRepository.find({ relations: ['readers'] }) };
        } catch {
            throw new HttpException(`Cannot GET /books`, HttpStatus.NOT_FOUND);
        }
    }

    async findOne(id: number) {
        try {
            await this.ensureBooksSchema();
            return {
                success: true,
                datas: await this.booksRepository.findOne({ where: { id: id }, relations: ['readers'] }),
            };
        } catch {
            throw new HttpException(`Cannot GET /books/${id}`, HttpStatus.NOT_FOUND);
        }
    }

    async catalog() {
        try {
            await this.ensureBooksSchema();
            const datas = await this.booksRepository.query(`
                SELECT
                    b.id,
                    b.name,
                    b.image,
                    b.description,
                    b.language,
                    b."readersId",
                    b.show_in_app,
                    b.likes_total,
                    b.do_not_likes_total,
                    b.year,
                    b.recommended_age,
                    jsonb_build_object('id', r.id, 'name', r.name) AS readers,
                    COALESCE(
                        jsonb_agg(DISTINCT jsonb_build_object('id', a.id, 'name', a.name))
                            FILTER (WHERE a.id IS NOT NULL),
                        '[]'::jsonb
                    ) AS authors,
                    COALESCE(
                        jsonb_agg(DISTINCT jsonb_build_object('id', c.id, 'name', c.name))
                            FILTER (WHERE c.id IS NOT NULL),
                        '[]'::jsonb
                    ) AS categories,
                    COALESCE((SELECT COUNT(DISTINCT m.name)::integer FROM manga_books m WHERE m."booksId" = b.id), 0) AS "mangaChapterCount",
                    COALESCE((SELECT COUNT(*)::integer FROM manga_books m WHERE m."booksId" = b.id), 0) AS "mangaPageCount",
                    COALESCE((SELECT COUNT(DISTINCT mh.name)::integer FROM manhwa_books mh WHERE mh."booksId" = b.id), 0) AS "manhwaChapterCount",
                    COALESCE((SELECT COUNT(*)::integer FROM manhwa_books mh WHERE mh."booksId" = b.id), 0) AS "manhwaPageCount",
                    (SELECT e.file FROM epub_books e WHERE e."booksId" = b.id ORDER BY e.id LIMIT 1) AS "epubFile",
                    (SELECT p.file FROM pdf_books p WHERE p."booksId" = b.id ORDER BY p.id LIMIT 1) AS "pdfFile"
                FROM books b
                LEFT JOIN readers r ON r.id = b."readersId"
                LEFT JOIN authors_books ab ON ab."booksId" = b.id
                LEFT JOIN authors a ON a.id = ab."authorsId"
                LEFT JOIN categories_books cb ON cb."booksId" = b.id
                LEFT JOIN categories c ON c.id = cb."categoreisId"
                WHERE COALESCE(b.show_in_app, true) = true
                GROUP BY b.id, r.id, r.name
                ORDER BY b.name ASC, b.id ASC
            `);

            return { success: true, datas };
        } catch {
            throw new HttpException(`Cannot GET /books/catalog`, HttpStatus.NOT_FOUND);
        }
    }

    async create(books: BooksModel, files) {
        try {
            await this.ensureBooksSchema();
            const old_books = await this.booksRepository.findOne({ where: { name: books.name } });
            if (!old_books || Number(old_books.id) === Number(books.id)) {
                if(files && files.image && files.image.length){
                    books.image = this.imagesService.saveImage(files.image[0]);
                }
                this.normalizeShowInApp(books, true);
                this.normalizeLanguage(books);
                books.likes_total = 0;
                books.do_not_likes_total = 0;
                return { success: true, datas: await this.booksRepository.save(books) };
            }
            return { success: false };
        } catch {
            throw new HttpException(`Cannot POST /books`, HttpStatus.NOT_FOUND);
        }
    }

    async reaction(id: number, body: { reaction?: string; previousReaction?: string }) {
        try {
            await this.ensureBooksSchema();
            const book = await this.booksRepository.findOne({ where: { id } });
            if (!book) {
                return { success: false };
            }

            const normalizeReaction = (value?: string) => {
                const reaction = String(value || '').trim().toLowerCase();
                return reaction === 'like' || reaction === 'dislike' ? reaction : 'none';
            };
            const previousReaction = normalizeReaction(body.previousReaction);
            const reaction = normalizeReaction(body.reaction);

            const likeDelta = (reaction === 'like' ? 1 : 0) - (previousReaction === 'like' ? 1 : 0);
            const dislikeDelta = (reaction === 'dislike' ? 1 : 0) - (previousReaction === 'dislike' ? 1 : 0);

            await this.booksRepository.query(
                `
                    UPDATE books
                    SET likes_total = GREATEST(0, COALESCE(likes_total, 0) + $1),
                        do_not_likes_total = GREATEST(0, COALESCE(do_not_likes_total, 0) + $2)
                    WHERE id = $3
                `,
                [likeDelta, dislikeDelta, id],
            );

            const updatedBook = await this.booksRepository.findOne({ where: { id } });
            return {
                success: true,
                datas: {
                    id,
                    likes_total: updatedBook?.likes_total ?? 0,
                    do_not_likes_total: updatedBook?.do_not_likes_total ?? 0,
                },
            };
        } catch {
            throw new HttpException(`Cannot POST /books/${id}/reaction`, HttpStatus.NOT_FOUND);
        }
    }

    async update(books: BooksModel, files) {
        try {
            await this.ensureBooksSchema();
            const old_books = await this.booksRepository.findOne({ where: { name: books.name } });
            if (!old_books || Number(old_books.id) === Number(books.id)) {
                if(files && files.image && files.image.length){
                    books.image = this.imagesService.saveImage(files.image[0]);
                }
                this.normalizeShowInApp(books);
                this.normalizeLanguage(books);
                return { success: true, datas: await this.booksRepository.update(books.id, books) };
            }
            return { success: false };
        } catch {
            throw new HttpException(`Cannot PUT /books`, HttpStatus.NOT_FOUND);
        }
    }

    async updateShowInApp(id: number, body: { show_in_app?: boolean }) {
        try {
            await this.ensureBooksSchema();
            const book = await this.booksRepository.findOne({ where: { id } });
            if (!book) {
                return { success: false };
            }

            const showInApp = this.booleanFromValue(body.show_in_app, true);
            await this.booksRepository.update(id, { show_in_app: showInApp });
            return { success: true, datas: { id, show_in_app: showInApp } };
        } catch {
            throw new HttpException(`Cannot PUT /books/${id}/show_in_app`, HttpStatus.NOT_FOUND);
        }
    }

    async delete(id: number) {
        try {
            await this.ensureBooksSchema();
            const books = await this.booksRepository.findOne({ where: { id: id } });
            if (books) {
                return { success: true, datas: await this.booksRepository.delete(id) };
            }
            return { success: false };
        } catch {
            throw new HttpException(`Cannot DELETE /books/${id}`, HttpStatus.NOT_FOUND);
        }
    }
}
